- alias: "Front door unlocked"
  trigger:
    platform: state
    entity_id: lock.schlage_be469nxcen_touchscreen_deadbolt_locked_6_0
    from: "locked"
    to: "unlocked"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.owntracks_spluntyphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.owntracks_spluntyphone
        state: 'work'
      - condition: state
        entity_id: device_tracker.owntracks_spluntyphone
        state: 'allergy'
  action:
    service: notify.notify_push_android
    data_template:
      message: "The front door was unlocked!"

- alias: "Change lock batteries"
  trigger:
    platform: numeric_state
    entity_id: sensor.front_dead_bolt_battery
    below: 10
  action:
    service: notify.notify_push_android
    data_template:
      message: "The deadbolt AA batteries are at {{ states.zwave.schlage_be469nxcen_touchscreen_deadbolt_6.attributes.battery_level }}%."

- alias: "Garage open for 10 minutes"
  trigger:
    platform: state
    entity_id: cover.garage_door
    state: "open"
    for:
       hours: 0
       minutes: 10
       seconds: 0
  action:
    service: notify.notify_push_android
    data_template:
       message: "Garage door has been open for 10 minutes!"

- alias: "front porch light on"
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_spluntyphone
    from: 'home'
    to: 'not_home'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_3_0
      data:
        brightness_pct: 100
    - service: notify.notify_push_android
      data_template:
        message: "You left home after dark. Front porch light on!"

- alias: "welcome home - front porch light off"
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_spluntyphone
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_3_0
      state: 'on'
  action:
    - service: notify.notify_push_android
      data_template:
        message: "Welcome home! Lights off in 15!"
    - delay: 00:15:00
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_3_0

- alias: "driveway light on"
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2_0
      data:
        brightness_pct: 100

- alias: "driveway light off"
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2_0

- alias: "back porch light on - door open after sunset"
  trigger:
    - platform: state
      entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor_5_0
      state: 'on'
      for:
        seconds: 1
    - platform: sun
      event: sunset
      offset: "+00:05:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor_5_0
        state: 'on'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
  action:
    - service: light.turn_on
      entity_id: light.ge_unknown_type4c42_id3031_level_9_0
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_8_0
    - service: notify.notify_push_android
      data_template:
        message: "Back porch light turned on."

- alias: "back porch light off - door shut"
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_unknown_type0004_id0002_sensor_5_0
    state: 'off'
    for:
      seconds: 1
  action:
    - service: light.turn_off
      entity_id: light.ge_unknown_type4c42_id3031_level_9_0
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_8_0

- alias: "unlock from door with nfc sticker"
  trigger:
    platform: state
    entity_id: sensor.front_door_mqtt
    from: "null"
    to: "unlock"
  action:
    - service: lock.unlock
      entity_id: lock.schlage_be469nxcen_touchscreen_deadbolt_locked_6_0
