- alias: "Garage open for 10 minutes"
  trigger:
    platform: state
    entity_id: cover.garage_door
    state: "open"
    for:
       hours: 0
       minutes: 10
       seconds: 0
  action:
    service: notify.notify_push_android
    data_template:
          message: "Garage door has been open for 10 minutes!"

- alias: "front porch light on"
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_spluntyphone
    from: 'home'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2_0
      data:
        brightness_pct: 10
        transition: 0
    - service: notify.notify_push_android
      data_template:
        message: "You left home after dark. Front porch light on!"

- alias: "welcome home - front porch light off"
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_spluntyphone
    to: 'home'
  condition:
    - condition: state
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2_0
      state: 'on'
  action:
    - service: notify.notify_push_android
      data_template:
        message: "Welcome home! Lights off in 15!"
    - delay: 00:15:00
    - service: light.turn_on
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2_0
      data:
        brightness_pct: 10
        transition: 0
    - delay: 00:00:01
    - service: light.turn_off
      entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2_0

