- alias: "Front door unlocked"
  trigger:
    platform: state
    entity_id: lock.front_deadbolt_locked
    from: "locked"
    to: "unlocked"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.owntracks_spluntyphone
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.owntracks_spluntyphone
        state: 'work'
      - condition: state
        entity_id: device_tracker.owntracks_spluntyphone
        state: 'allergy'
  action:
    service: notify.notify_push_android
    data_template:
      message: "The front door was unlocked!"

- alias: "Change lock batteries"
  trigger:
    platform: numeric_state
    entity_id: sensor.front_dead_bolt_battery
    below: 10
  action:
    service: notify.notify_push_android
    data_template:
      message: "The deadbolt AA batteries are at {{ states.zwave.front_deadbolt.attributes.battery_level }}%."

- alias: "Garage open for 10 minutes"
  trigger:
    platform: state
    entity_id: cover.garage_door
    state: "open"
    for:
       hours: 0
       minutes: 10
       seconds: 0
  action:
    service: notify.notify_push_android
    data_template:
       message: "Garage door has been open for 10 minutes!"

- alias: "front porch light on"
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_spluntyphone
    from: 'home'
    to: 'not_home'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      entity_id: light.front_porch_light_level
      data:
        brightness_pct: 100
    - service: notify.notify_push_android
      data_template:
        message: "You left home after dark. Front porch light on!"

- alias: "welcome home - front porch light off"
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_spluntyphone
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: light.front_porch_light_level
      state: 'on'
  action:
    - service: notify.notify_push_android
      data_template:
        message: "Welcome home! Lights off in 15!"
    - delay: 00:15:00
    - service: light.turn_off
      entity_id: light.front_porch_light_level

- alias: "driveway light on, lizard cage off"
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      entity_id: light.driveway_light_level
      data:
        brightness_pct: 100
    - service: switch.turn_off
      entity_id: switch.outlet_lizard_cage_switch

- alias: "driveway light off, lizard cage on"
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: light.turn_off
      entity_id: light.driveway_light_level
    - service: switch.turn_on
      entity_id: switch.outlet_lizard_cage_switch

- alias: "back porch light on - door open after sunset"
  trigger:
    - platform: state
      entity_id: binary_sensor.contact_back_door_sensor
      state: 'on'
      for:
        seconds: 1
    - platform: sun
      event: sunset
      offset: "+00:05:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.contact_back_door_sensor
        state: 'on'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
          - condition: sun
            before: sunrise
  action:
    - service: light.turn_on
      entity_id: light.back_porch_light_2_level
    - service: light.turn_on
      entity_id: light.back_porch_light_1_level

- alias: "back porch light off - door shut"
  trigger:
    platform: state
    entity_id: binary_sensor.contact_back_door_sensor
    state: 'off'
    for:
      seconds: 1
  action:
    - service: light.turn_off
      entity_id: light.back_porch_light_2_level
    - service: light.turn_off
      entity_id: light.back_porch_light_1_level

- alias: "unlock from door with nfc sticker"
  trigger:
    platform: state
    entity_id: sensor.front_door_mqtt
    from: "null"
    to: "unlock"
  action:
    - service: lock.unlock
      entity_id: lock.front_deadbolt_locked

- alias: "garage light on for 10 minutes"
  trigger:
    platform: state
    entity_id: binary_sensor.contact_garage_door_sensor
    state: 'on'
  condition:
    - condition: state
      entity_id: light.garage_light_level
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.garage_light_level
    - delay: 00:10:00
    - service: light.turn_off
      entity_id: light.garage_light_level
