- alias: "Garage open for 10 minutes"
  trigger:
    platform: state
    entity_id: cover.garage_door
    state: "open"
    for:
       hours: 0
       minutes: 10
       seconds: 0
  action:
    service: notify.notify_push_android
    data_template:
          message: "Garage door has been open for 10 minutes!"

- alias: "Turn on porch light"
  trigger:
    platform: state
    entity_id: device_tracker.owntracks_spluntyphone
    from: 'home'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: light.turn_on
      entity_id: light.frontporchzwavebulb_level_2_0
    - service: notify.notify_push_android
      data_template:
        message: "You left home. Front porch light on!"

- alias: "Turn off porch light"
  trigger:
    platform: time
    after: '02:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'device_tracker.owntracks_spluntyphone'
        state: 'home'
      - condition: state
        entity_id: light.frontporchzwavebulb_level_2_0
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.frontporchzwavebulb_level_2_0
    #- service: notify.notify_push_android
    #  data_template:
    #    message: "You are home. Front porch light off!"

