homeassistant:
  name: Home
  customize: !include customize.yaml
  unit_system: imperial
  latitude: secret
  longitude: secret
  elevation: 103
  time_zone: America/Chicago

frontend: # Enables the frontend
logbook:  # View all events in a logbook
updater:  # Checks for available updates
history:  # Enables support for tracking state changes over time.
sun:      # Track the sun

http:
  api_password: secret

mqtt:
  broker: secret
  port: 1883
  keepalive: 60
  username: owntracks
  password: secret

notify:
  platform: pushbullet
  api_key: secret
  name: notify_push_android

#zone Home:
#  name: Home
#  latitude: secret
#  longitude: secret
#  radius: 100 
#  icon: mdi:home

zone Work:
  name: work
  latitude: secret
  longitude: secret
  radius: 250
  icon: mdi:worker

zone Allergy:
  name: allergy
  latitude: secret
  longitude: secret
  radius: 200
  icon: mdi:needle

proximity:
  home:
    devices:
      - device_tracker.owntracks_spluntyphone
    tolerance: 50
    unit_of_measurement: mi

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 50

light:
  platform: limitlessled
  bridges:
  - host: 10.10.10.8
    version: 5
    port: 8899
    groups:
    - number: 1
      type: rgbw
      name: tv_led
    - number: 2
      type: rgbw
      name: bedroom_led
    - number: 3
      type: rgbw
      name: livingroom_led

weblink:
  entities:
    - name: andrew_ha
      url: secret
      icon: mdi:chair-school
    - name: pics
      url: secret
      icon: mdi:google-photos
    - name: purge_pics
      url: secret
      icon: mdi:shovel

emulated_hue:
  type: alexa
  host_ip: 10.10.10.201
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - script
    - light
    - scene

camera 1:
  platform: foscam
  ip: 10.10.10.16
  name: frontcam
  port: 88
  username: admin
  password: secret

camera 2:
  platform: foscam
  ip: 10.10.10.17
  name: backcam
  port: 88
  username: admin
  password: secret

cover:
  - platform: mqtt
    name: "Garage Door"
    state_topic: "sensor/garage_door"
    command_topic: "cmd/garage_door"

zwave:
  usb_path: /dev/ttyACM0
  device_config:
    light.ge_unknown_type4c42_id3031_level_9_0: # back porch light 2
      refresh_value: true
      delay: 3
    light.linear_lb60z1_dimmable_led_light_bulb_level_2_0: # driveway
      refresh_value: true
      delay: 3
    light.linear_lb60z1_dimmable_led_light_bulb_level_3_0: # front porch
      refresh_value: true
      delay: 3
    light.linear_lb60z1_dimmable_led_light_bulb_level_7_0: # garage
      refresh_value: true
      delay: 3
    light.linear_lb60z1_dimmable_led_light_bulb_level_8_0: # back porch 1
      refresh_value: true
      delay: 3

alexa: !include alexa.yaml
automation: !include automation.yaml
group: !include group.yaml
input_boolean: !include input_boolean.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
#shell_command: !include shell_command.yaml
#switch: !include switches.yaml

